# Naive Bayes & NLP - Assignment

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.utils import shuffle

from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

import nltk
from nltk.corpus import stopwords
import re #regular expressions
from bs4 import BeautifulSoup
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

## PART 1 - Sentiment analysis 

Classify the sentiment of text messages as being positive or negative.
The training data and test data can be found in:  *sentiment_train.csv* and *sentiment_test.csv*.

Follow these steps:

1. Analys of the data.
2. Preprocessing of the text.
3. Convert to bag-of-words.
4. Training the classifiers.
5. Testing and hyperparameter tuning.

In [3]:
# Import the datasets

dataset_train = pd.read_csv('sentiment_train.csv')
dataset_test = pd.read_csv('sentiment_test.csv')

dataset_train.head()

   sentiment                                               text
0          1            The Da Vinci Code book is just awesome.
1          0   Oh, and Brokeback Mountain was a terrible movie.
2          1  He's like,'YEAH I GOT ACNE AND I LOVE BROKEBAC...
3          1  1st and 2nd Harry Potter movies are clearly th...
4          0             Mission Impossible 3 was quite boring.

### 1. Analysis of the data

- Look for missing values.
- Is the dataset balanced?
- Is there a correlation between the length of a text and the sentiment?

In [ ]:
# analysis of the data

### 2. Preprocessing of the text

- clean the text: remove stopwords, non-literal characters, ... 
- Apply stemming.

In [ ]:
# Preprocessing of the text

### 3. Convert to bag-of-words

Use the CountVectorizer and TfidfTransformer to create a bag-of-words model. 

More info: 

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html 

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html#sklearn.feature_extraction.text.TfidfTransformer 

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html#sklearn.feature_extraction.text.TfidfVectorizer

In [ ]:
# Convert to bag-of-words

### 4. Train the classifiers

Train 3 different types of classifiers: naive bayes classifier, logistic regression classifier and a Support Vector Machine classifier.

In [ ]:
# Train naive bayes, logistic regression, SVM

### 5. Testing and hyperparameter tuning

- Use grid-search, random search or Bayes Optimization for hyperparameter tuning.
- Which classifier has the best performance? bring arguments in terms of f1-score and computational time.

In [ ]:
# Testing and hyperparameter tuning

## PART 2  - Sarcasm detection

Train a classifier to detect sarcasm in newspaper headlines.

Use the 'Sarcasm.json' dataset.

Train, evaluate and compare naive bayes, logistic regression and support vector machines

In [4]:
dataset = pd.read_json('Sarcasm.json')
dataset.head()

                                               headline  is_sarcastic
0     former versace store clerk sues over secret 'b...             0
1     the 'roseanne' revival catches up to our thorn...             0
10    airline passengers tackle man who rushes cockp...             0
100   demi lovato drops emotional 'nightingale' musi...             0
1000  california marijuana businesses get their firs...             0